// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Auth.proto
// Protobuf Java Version: 4.31.0

package com.zslt_official.zslt_eco.grpc.v1;

@com.google.protobuf.Generated
public final class Auth {
  private Auth() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      Auth.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_auth_v1_GetTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_auth_v1_GetTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_auth_v1_GetTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_auth_v1_GetTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_auth_v1_RefreshTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_auth_v1_RefreshTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_auth_v1_RefreshTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_auth_v1_RefreshTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_auth_v1_RevokeTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_auth_v1_RevokeTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_auth_v1_RevokeTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_auth_v1_RevokeTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_auth_v1_ValidateTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_auth_v1_ValidateTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_auth_v1_ValidateTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_auth_v1_ValidateTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nAuth.proto\022\013api.auth.v1\"7\n\017GetTokenReq" +
      "uest\022\017\n\007user_id\030\001 \001(\t\022\023\n\013server_name\030\002 \001" +
      "(\t\"r\n\020GetTokenResponse\022\017\n\007success\030\001 \001(\010\022" +
      "\017\n\007message\030\002 \001(\t\022\024\n\014access_token\030\003 \001(\t\022\025" +
      "\n\rrefresh_token\030\004 \001(\t\022\017\n\007user_id\030\005 \001(\t\"," +
      "\n\023RefreshTokenRequest\022\025\n\rrefresh_token\030\001" +
      " \001(\t\"e\n\024RefreshTokenResponse\022\017\n\007success\030" +
      "\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\024\n\014access_token\030\003" +
      " \001(\t\022\025\n\rrefresh_token\030\004 \001(\t\"R\n\022RevokeTok" +
      "enRequest\022\017\n\007user_id\030\001 \001(\t\022\023\n\013server_nam" +
      "e\030\002 \001(\t\022\026\n\016token_category\030\003 \001(\t\"7\n\023Revok" +
      "eTokenResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007messa" +
      "ge\030\002 \001(\t\"=\n\024ValidateTokenRequest\022\r\n\005toke" +
      "n\030\001 \001(\t\022\026\n\016token_category\030\002 \001(\t\"n\n\025Valid" +
      "ateTokenResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007mes" +
      "sage\030\002 \001(\t\022\r\n\005valid\030\003 \001(\010\022\017\n\007user_id\030\004 \001" +
      "(\t\022\023\n\013server_name\030\005 \001(\t2\325\002\n\013AuthService\022" +
      "G\n\010GetToken\022\034.api.auth.v1.GetTokenReques" +
      "t\032\035.api.auth.v1.GetTokenResponse\022S\n\014Refr" +
      "eshToken\022 .api.auth.v1.RefreshTokenReque" +
      "st\032!.api.auth.v1.RefreshTokenResponse\022P\n" +
      "\013RevokeToken\022\037.api.auth.v1.RevokeTokenRe" +
      "quest\032 .api.auth.v1.RevokeTokenResponse\022" +
      "V\n\rValidateToken\022!.api.auth.v1.ValidateT" +
      "okenRequest\032\".api.auth.v1.ValidateTokenR" +
      "esponseBC\n*com.zslt_official.zslt_eco.gr" +
      "pc.service.v1P\001Z\023auth/api/auth/v1;v1b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_api_auth_v1_GetTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_auth_v1_GetTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_auth_v1_GetTokenRequest_descriptor,
        new java.lang.String[] { "UserId", "ServerName", });
    internal_static_api_auth_v1_GetTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_auth_v1_GetTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_auth_v1_GetTokenResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "AccessToken", "RefreshToken", "UserId", });
    internal_static_api_auth_v1_RefreshTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_auth_v1_RefreshTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_auth_v1_RefreshTokenRequest_descriptor,
        new java.lang.String[] { "RefreshToken", });
    internal_static_api_auth_v1_RefreshTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_auth_v1_RefreshTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_auth_v1_RefreshTokenResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "AccessToken", "RefreshToken", });
    internal_static_api_auth_v1_RevokeTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_api_auth_v1_RevokeTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_auth_v1_RevokeTokenRequest_descriptor,
        new java.lang.String[] { "UserId", "ServerName", "TokenCategory", });
    internal_static_api_auth_v1_RevokeTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_api_auth_v1_RevokeTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_auth_v1_RevokeTokenResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_api_auth_v1_ValidateTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_api_auth_v1_ValidateTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_auth_v1_ValidateTokenRequest_descriptor,
        new java.lang.String[] { "Token", "TokenCategory", });
    internal_static_api_auth_v1_ValidateTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_api_auth_v1_ValidateTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_auth_v1_ValidateTokenResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Valid", "UserId", "ServerName", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
