// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Auth.proto
// Protobuf Java Version: 4.31.0

package com.zslt_official.zslt_eco.grpc.v1;

@com.google.protobuf.Generated
public interface ValidateTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.auth.v1.ValidateTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>bool valid = 3;</code>
   * @return The valid.
   */
  boolean getValid();

  /**
   * <code>string user_id = 4;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 4;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string server_name = 5;</code>
   * @return The serverName.
   */
  java.lang.String getServerName();
  /**
   * <code>string server_name = 5;</code>
   * @return The bytes for serverName.
   */
  com.google.protobuf.ByteString
      getServerNameBytes();
}
