// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"email/internal/biz"
	"email/internal/conf"
	"email/internal/data"
	"email/internal/server"
	"email/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, confRegistry *conf.Registry, confEmail *conf.Email) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger, data.NewDatabase(confData))
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)

	dataRepo := data.NewDataRepo(dataData, logger)
	emailUsecase := biz.NewEmailUsecase(dataRepo, logger)
	emailService := service.NewEmailService(emailUsecase, confEmail)

	grpcServer := server.NewGRPCServer(confServer, greeterService, emailService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)

	// 服务注册
	registrar := server.NewRegistrar(confRegistry)
	server.RegisterHealthCheck(httpServer)

	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
