// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Auth.proto
// Protobuf Java Version: 4.31.0

package com.zslt_official.zslt_eco.grpc.v1.service;

@com.google.protobuf.Generated
public interface RefreshTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.auth.v1.RefreshTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string refresh_token = 1;</code>
   * @return The refreshToken.
   */
  java.lang.String getRefreshToken();
  /**
   * <code>string refresh_token = 1;</code>
   * @return The bytes for refreshToken.
   */
  com.google.protobuf.ByteString
      getRefreshTokenBytes();
}
