// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Auth.proto
// Protobuf Java Version: 4.31.0

package com.zslt_official.zslt_eco.grpc.v1.service;

@com.google.protobuf.Generated
public interface RevokeTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.auth.v1.RevokeTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
