// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Auth.proto
// Protobuf Java Version: 4.31.0

package com.zslt_official.zslt_eco.grpc.v1.service;

@com.google.protobuf.Generated
public interface ValidateTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.auth.v1.ValidateTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   * "at" 或 "rt"
   * </pre>
   *
   * <code>string token_category = 2;</code>
   * @return The tokenCategory.
   */
  java.lang.String getTokenCategory();
  /**
   * <pre>
   * "at" 或 "rt"
   * </pre>
   *
   * <code>string token_category = 2;</code>
   * @return The bytes for tokenCategory.
   */
  com.google.protobuf.ByteString
      getTokenCategoryBytes();
}
