server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

registry:
  consul:
    address:
      - 127.0.0.1:8500
    scheme: http

data:
  database:
    driver: mysql
    source: root:password@tcp(127.0.0.1:3306)/email?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

email:
  host: smtp.qq.com
  port: 465
